# Generated by Django 6.0.3 on 2026-03-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allow_comments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='awards',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='certifications',
            field=models.TextField(blank=True, default='', help_text='e.g. AWS Solutions Architect, Docker DCA', max_length=1000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cloud_platforms',
            field=models.CharField(blank=True, default='', help_text='e.g. AWS, GCP, Azure', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.CharField(blank=True, default='', help_text='Company or Organization', max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_role',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('developer', 'Developer'), ('researcher', 'Researcher'), ('engineer', 'Engineer'), ('designer', 'Designer'), ('data_scientist', 'Data Scientist'), ('devops', 'DevOps Engineer'), ('freelancer', 'Freelancer'), ('other', 'Other')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='databases',
            field=models.CharField(blank=True, default='', help_text='e.g. PostgreSQL, MongoDB, Redis', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='degree',
            field=models.CharField(blank=True, default='', help_text='Degree and Field of Study', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='devops_tools',
            field=models.CharField(blank=True, default='', help_text='e.g. Docker, Kubernetes, Jenkins', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='devto_handle',
            field=models.CharField(blank=True, default='', help_text='Dev.to or Medium handle', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_technologies',
            field=models.CharField(blank=True, default='', help_text='e.g. Django, TensorFlow, React', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='frameworks',
            field=models.CharField(blank=True, default='', help_text='e.g. Django, React, Flask', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hackathons',
            field=models.TextField(blank=True, default='', help_text='Hackathons you have participated in', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='kaggle_handle',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='languages',
            field=models.CharField(blank=True, default='', help_text='e.g. Python, JavaScript, Go', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, default='', help_text='City, Country', max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='open_source_contributions',
            field=models.TextField(blank=True, default='', help_text='Describe your open-source contributions', max_length=1000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='open_to_opportunities',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='operating_systems',
            field=models.CharField(blank=True, default='', help_text='e.g. Linux, macOS, Windows', max_length=300),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='projects',
            field=models.TextField(blank=True, default='', help_text='Highlight notable projects', max_length=1500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='publications',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skill_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.TextField(blank=True, default='', help_text='e.g. Backend Development, Machine Learning, Cloud Computing', max_length=1000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stackoverflow_url',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='top_repositories',
            field=models.TextField(blank=True, default='', help_text='List your top open-source repositories', max_length=1000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='topics_of_interest',
            field=models.CharField(blank=True, default='', help_text='e.g. AI, Web Development, DevOps, Cybersecurity', max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitter_handle',
            field=models.CharField(blank=True, default='', help_text='Twitter / X handle', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='university',
            field=models.CharField(blank=True, default='', help_text='University or College', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='website',
            field=models.URLField(blank=True, default='', help_text='Personal portfolio or website'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='writing_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
