# Generated by Django 6.0.3 on 2026-03-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_userprofile_allow_comments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='bio',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_picture',
            new_name='profile_image',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='facebook_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instagram_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitter_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='youtube_link',
            field=models.URLField(blank=True, default=''),
        ),
    ]
