# Generated by Django 6.0.3 on 2026-03-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_rename_bio_userprofile_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='privacy_setting',
            field=models.CharField(default='public', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_banner',
            field=models.ImageField(blank=True, null=True, upload_to='profile_banners/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='public_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
