# Generated by Django 6.0.3 on 2026-03-15 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_userprofile_company_userprofile_current_role_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friend_requests', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friend_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['receiver', 'status'], name='profiles_fr_receive_15527f_idx'), models.Index(fields=['sender', 'status'], name='profiles_fr_sender__806915_idx'), models.Index(fields=['created_at'], name='profiles_fr_created_06f8d6_idx')],
                'constraints': [models.UniqueConstraint(fields=('sender', 'receiver'), name='unique_friend_request_pair'), models.CheckConstraint(condition=models.Q(('sender', models.F('receiver')), _negated=True), name='no_self_friend_request')],
            },
        ),
    ]
