# Generated by Django 6.0.3 on 2026-03-15 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_tag_blog_difficulty_level_blog_is_ai_reference_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='allow_comments',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='allow_likes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='citation',
            field=models.TextField(blank=True, default='', help_text='Attribution or citation for the content'),
        ),
        migrations.AddField(
            model_name='blog',
            name='scheduled_publish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='blog',
            name='visibility',
            field=models.CharField(choices=[('Public', 'Public'), ('Unlisted', 'Unlisted'), ('Private', 'Private')], default='Public', max_length=20),
        ),
        migrations.CreateModel(
            name='SavedWikiArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('extract', models.TextField(blank=True, default='')),
                ('thumbnail', models.URLField(blank=True, default='', max_length=500)),
                ('original_url', models.URLField(blank=True, default='', max_length=500)),
                ('html_content', models.TextField(blank=True, default='')),
                ('board_column', models.CharField(choices=[('Inbox', 'Inbox'), ('Reading', 'Reading'), ('Completed', 'Completed')], default='Inbox', max_length=20)),
                ('board_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_wiki_articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['board_order'],
                'unique_together': {('user', 'title')},
            },
        ),
    ]
