from django.db import migrations


PREDEFINED_TECH_CATEGORIES = [
    "Programming & Development",
    "Programming Basics",
    "Python",
    "JavaScript",
    "TypeScript",
    "Java",
    "C Programming",
    "C++",
    "Go (Golang)",
    "Rust",
    "Kotlin",
    "Swift",
    "PHP",
    "Ruby",
    "Shell Scripting",
    "Assembly Language",
    "Web Development",
    "Frontend Development",
    "Backend Development",
    "Full Stack Development",
    "HTML",
    "CSS",
    "Tailwind CSS",
    "Bootstrap",
    "Web Performance",
    "Progressive Web Apps",
    "JavaScript Frameworks",
    "React",
    "Next.js",
    "Angular",
    "Vue.js",
    "Svelte",
    "Remix",
    "Astro",
    "SolidJS",
    "jQuery",
    "Alpine.js",
    "Backend Frameworks",
    "Django",
    "Flask",
    "FastAPI",
    "Node.js",
    "Express.js",
    "Spring Boot",
    "Laravel",
    "Ruby on Rails",
    "NestJS",
    "ASP.NET",
    "Mobile Development",
    "Android Development",
    "iOS Development",
    "Flutter",
    "React Native",
    "SwiftUI",
    "Kotlin Multiplatform",
    "Mobile UI Design",
    "Cross Platform Apps",
    "Mobile Performance",
    "Databases",
    "SQL",
    "PostgreSQL",
    "MySQL",
    "SQLite",
    "MongoDB",
    "Redis",
    "Cassandra",
    "DynamoDB",
    "Database Optimization",
    "DevOps & Infrastructure",
    "DevOps",
    "CI/CD",
    "Docker",
    "Kubernetes",
    "Terraform",
    "Infrastructure as Code",
    "Ansible",
    "Jenkins",
    "GitHub Actions",
    "Monitoring",
    "Cloud Computing",
    "AWS",
    "Microsoft Azure",
    "Google Cloud",
    "Serverless",
    "Cloud Architecture",
    "Cloud Security",
    "Cloud Databases",
    "Edge Computing",
    "Multi Cloud",
    "Artificial Intelligence",
    "Machine Learning",
    "Deep Learning",
    "Neural Networks",
    "Natural Language Processing",
    "Computer Vision",
    "Generative AI",
    "Reinforcement Learning",
    "AI Ethics",
    "AI Tools",
    "Data Science",
    "Data Analysis",
    "Data Visualization",
    "Big Data",
    "Pandas",
    "NumPy",
    "Data Engineering",
    "ETL Pipelines",
    "Data Mining",
    "Statistics",
    "Cybersecurity",
    "Ethical Hacking",
    "Network Security",
    "Application Security",
    "Cryptography",
    "Malware Analysis",
    "Security Tools",
    "Bug Bounty",
    "Digital Forensics",
    "Privacy",
    "Blockchain",
    "Cryptocurrency",
    "Smart Contracts",
    "Web3",
    "NFTs",
    "DeFi",
    "Ethereum",
    "Solana",
    "Blockchain Development",
    "Blockchain Security",
    "Internet of Things",
    "Embedded Systems",
    "Arduino",
    "Raspberry Pi",
    "Smart Devices",
    "Sensor Networks",
    "Edge AI",
    "IoT Security",
    "Industrial IoT",
    "Robotics",
    "Software Engineering",
    "Software Architecture",
    "Design Patterns",
    "System Design",
    "Code Quality",
    "Refactoring",
    "Clean Code",
    "Agile Development",
    "Scrum",
    "Testing",
    "Unit Testing",
    "Integration Testing",
    "End-to-End Testing",
    "Test Automation",
    "Selenium",
    "Cypress",
    "Jest",
    "PyTest",
    "Load Testing",
    "Performance Testing",
    "Version Control",
    "Git",
    "GitHub",
    "GitLab",
    "Bitbucket",
    "Operating Systems",
    "Linux",
    "Windows Development",
    "macOS Development",
    "Kernel Development",
    "Networking",
    "TCP/IP",
    "HTTP Protocol",
    "WebSockets",
    "DNS",
    "UI/UX & Design",
    "UI Design",
    "UX Design",
    "Product Design",
    "Design Systems",
    "Accessibility",
    "Developer Career",
    "Programming Tips",
    "Coding Interview Prep",
    "Open Source",
    "Developer Tools",
    "Tech Career",
    "Emerging Technologies",
    "Quantum Computing",
    "Augmented Reality",
    "Virtual Reality",
    "Metaverse",
    "Digital Twins",
    "Hardware & Systems",
    "Computer Architecture",
    "GPU Computing",
    "Parallel Computing",
    "High Performance Computing",
    "Distributed Systems",
    "Misc Tech",
    "API Development",
    "Microservices",
    "SaaS Development",
    "Tech Startups",
    "Productivity Tools",
    "Automation",
    "Tech News",
    "Tutorials",
    "Case Studies",
    "Best Practices",
]


def seed_predefined_categories(apps, schema_editor):
    Category = apps.get_model('blogs', 'Category')
    existing_names = {
        name.lower()
        for name in Category.objects.values_list('category_name', flat=True)
    }

    new_categories = [
        Category(category_name=name)
        for name in PREDEFINED_TECH_CATEGORIES
        if name.lower() not in existing_names
    ]

    if new_categories:
        Category.objects.bulk_create(new_categories)


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_blog_allow_comments_blog_allow_likes_blog_citation_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_predefined_categories, migrations.RunPython.noop),
    ]
