# Generated by Django 6.0.3 on 2026-03-21 20:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_cluster_wiki_articles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['status', '-created_at'], name='blogs_blog_status_0452e8_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['author', 'status', '-created_at'], name='blogs_blog_author__cf5e7c_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['source_type', 'status'], name='blogs_blog_source__d024bb_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['is_featured', '-created_at'], name='blogs_blog_is_feat_a667a4_idx'),
        ),
        migrations.AddIndex(
            model_name='blog',
            index=models.Index(fields=['view_count'], name='blogs_blog_view_co_0a503d_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['blog', '-created_at'], name='blogs_comme_blog_id_50f3bc_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user', '-created_at'], name='blogs_comme_user_id_93366a_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user', '-created_at'], name='blogs_favor_user_id_11f781_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['blog'], name='blogs_favor_blog_id_a2a502_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['blog'], name='blogs_like_blog_id_9d05d2_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['user', '-created_at'], name='blogs_like_user_id_7966c6_idx'),
        ),
        migrations.AddIndex(
            model_name='savedwikiarticle',
            index=models.Index(fields=['user', 'board_column', 'board_order'], name='blogs_saved_user_id_a04bdd_idx'),
        ),
        migrations.AddIndex(
            model_name='savedwikiarticle',
            index=models.Index(fields=['user', '-updated_at'], name='blogs_saved_user_id_d48201_idx'),
        ),
        migrations.AddIndex(
            model_name='savedwikiarticle',
            index=models.Index(fields=['user', 'liked'], name='blogs_saved_user_id_8b21dc_idx'),
        ),
    ]
